### ISSUE TITLE
Maybe allow for icount start and stop values to be supplied as cmd args.

### ISSUE THREAD

**Issue by thakkarV** [travisdowns/robsize#1]
Currently, the instruction count is supplied through environment variables START and STOP, but for the purposes of easier automation of tests and reducing test times, if would be awesome if these could be supplied as arguments to robsize itself.

**Comment by travisdowns** [comment]
@thakkarV - I just did it that way because I'm lazy (and didn't want to handle all the cases in the parsing code), but I I think environment variables are just as easy 'cause you can set them on a per-command basis?

E.g. instead of this:

~~~
for i in {100..200}; do
  ./robsize --start $i
done
~~~

you do


~~~
for i in {100..200}; do
  START=$i ./robsize
done
~~~

Or maybe I'm missing the scenario you are thinking of?

**Comment by thakkarV** [comment]
Yeah I agree, and I am not really proposing this as a change, but whenever I see a command line utility, I go directly to the command line options to see how I can configure this. In my subjective opinion, env vars make it somewhat opaque and more magic number-y.

**Comment by travisdowns** [comment]
I agree, but I am lazy to change it - pull requests gladly accepted though :).

The code is in `handle_args`.

**Comment by thakkarV** [comment]
A PR will be gladly made! ETA 24 hours

**Comment by thakkarV** [comment]
Is it okay if I convert the arg parsing to use get_opt_long instead of the manual strcmp? I can just tack on the start and stop to the current manual parsing, but the new args require an int arg to follow after them and we would have to settle on argv+1 being that int, and if a user supplies something like --start=n that would not work.

**Comment by thakkarV** [comment]
Another thing is noticed is the reuse of the `start` and `stop` variable names. First, start and stop are defined as icount range values as type int. (robsize.cc:502)
```cpp
int start = getenv_int("START", print_ibuf ? 33 : 16);
int stop  = getenv_int("STOP", 250);
```

But within the loop that is bounded by these start and stop icount `int`s,  we store the `rdtsc()` counter to start and stop of type `long long`. (robsize.cc:516)
```cpp
long long start = rdtsc();
routine_skip();
long long stop = rdtsc();
```

I assume this is not intentional?

**Comment by travisdowns** [comment]
> Is it okay if I convert the arg parsing to use get_opt_long instead of the manual strcmp? I can just tack on the start and stop to the current manual parsing, but the new args require an int arg to follow after them and we would have to settle on argv+1 being that int, and if a user supplies something like --start=n that would not work.

Sure, go ahead.

**Comment by travisdowns** [comment]
> I assume this is not intentional?

No, but apparently it works!

The `start` and `stop` used for timing are not in scope at the point the loop condition is evaluated, so each place is using the right variables (or else it would be totally bused), but I agree we should fix this name clash. Feel free to rename either one.

**Comment by thakkarV** [comment]
Sorry for the commit spam, but the PR over at GH-4 should address both of these!

**Comment by thakkarV** [comment]
closed by GH-4
